<?php

namespace BlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	public function getById($id)
	{
		$query = $this->createQueryBuilder('a')
			->setParameter('id', $id)
			->where('a.id = :id')
			->getQuery();

		return $query->getSingleResult();
	}

	public function getAll()
	{
		$query = $this->createQueryBuilder('a')
   				->orderBy('a.date', 'DESC')
				->getQuery();

		return $query->getResult();
	}
}