<?php

namespace BlogBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
	public function getByIdArticle($id)
	{
		$query = $this->createQueryBuilder('c')
			->setParameter('id', $id)
			->where('c.article = :id')
			->getQuery();

		return $query->getResult();
	}
}